---
title: "1.1.2_Vectors_DataFrames"
output: html_document
date: "2023-02-22"
---

# Vectors

```{r}
# Numeric
c(1, 4, 6, 3, 2, 6, 4)

# Character
c("Nice", "2", "meet", "you")
```

Working with numeric vectors

```{r}
v <- c(1, 4, 6, 3, 2, 6, 4)
v
v + 10
sqrt(v)
mean(v)
sd(v) # standard deviation
```

Grabbing from a vector

```{r}
# grab the 5th value
v[5]

# grab 2nd and 4th values
v[c(2, 4)]

# grab all except 2nd and 4th value
v[-c(2, 4)] # use minus sign to exclude

# grab last value then the 3rd value twice
v[c(length(v), 3, 3)]

# vector of vector
v[v]
```

Integer sequences

```{r}
1:20
7:-7
```

# DataFrames

```{r}
d <- data.frame(Name = c("Carl", "Rae"), Age = c(36, 35))
```

Column referencing

```{r}
d$Name
d$Age

d$Job <- c("Actuary", "Analyst")
d
```

Grabbing from a dataframe

```{r}
d[1, 3] # row = 1, column = 3
d[2, ] # row = 2, all columns (displays as data.frame)
d[, "Age"] # all rows, Age column
d[1:2, c(1, 3)]
```




